const wordsByLesson = {
    1: [
        {hanzi: "八", pinyin: "bā", italiano: "Otto"},
        {hanzi: "不", pinyin: "bù", italiano: "No, non"},
        {hanzi: "大", pinyin: "dà", italiano: "Grande"},
        {hanzi: "力", pinyin: "lì", italiano: "Forza"},
        {hanzi: "马", pinyin: "mǎ", italiano: "Cavallo"},
        {hanzi: "米", pinyin: "mǐ", italiano: "Riso"},
        {hanzi: "木", pinyin: "mù", italiano: "Legno"},
        {hanzi: "女", pinyin: "nǚ", italiano: "Donna"},
        {hanzi: "一", pinyin: "yī", italiano: "Uno"}
    ],
    2: [
        {hanzi: "爸爸", pinyin: "bàba", italiano: "Papà"},
        {hanzi: "口", pinyin: "kǒu", italiano: "Bocca, apertura"},
        {hanzi: "妈妈", pinyin: "māma", italiano: "Mamma"},
        {hanzi: "你好", pinyin: "nǐ hǎo", italiano: "Ciao, salve"}
    ],
    3: [
        {hanzi: "汉语", pinyin: "hànyǔ", italiano: "Lingua cinese"},
        {hanzi: "课", pinyin: "kè", italiano: "Lezione"},
        {hanzi: "现在", pinyin: "xiànzài", italiano: "Adesso, ora"},
        {hanzi: "谢谢", pinyin: "xièxie", italiano: "Grazie"},
        {hanzi: "学习", pinyin: "xuéxí", italiano: "Studiare"},
        {hanzi: "再见", pinyin: "zàijiàn", italiano: "Arrivederci"}
    ],
    4: [
        {hanzi: "安静", pinyin: "ānjìng", italiano: "Tranquillo, silenzioso"},
        {hanzi: "吃饭", pinyin: "chīfàn", italiano: "Mangiare"},
        {hanzi: "老师", pinyin: "lǎoshī", italiano: "Insegnante"},
        {hanzi: "你", pinyin: "nǐ", italiano: "Tu, te"},
        {hanzi: "你们", pinyin: "nǐmen", italiano: "Voi"},
        {hanzi: "请", pinyin: "qǐng", italiano: "Invitare"},
        {hanzi: "他", pinyin: "tā", italiano: "Egli, lui"},
        {hanzi: "她", pinyin: "tā", italiano: "Ella, lei"},
        {hanzi: "他们", pinyin: "tāmen", italiano: "Loro, li"},
        {hanzi: "她们", pinyin: "tāmen", italiano: "Loro, le"},
        {hanzi: "我", pinyin: "wǒ", italiano: "Io, me"},
        {hanzi: "我们", pinyin: "wǒmen", italiano: "Noi, ci"},
        {hanzi: "小", pinyin: "xiǎo", italiano: "Piccolo"},
        {hanzi: "休息", pinyin: "xiūxi", italiano: "Riposare"},
        {hanzi: "学生", pinyin: "xuésheng", italiano: "Studente"},
        {hanzi: "对不起", pinyin: "duìbuqǐ", italiano: "Chiedere scusa"},
        {hanzi: "二", pinyin: "èr", italiano: "Due"},
        {hanzi: "三", pinyin: "sān", italiano: "Tre"},
        {hanzi: "四", pinyin: "sì", italiano: "Quattro"},
        {hanzi: "五", pinyin: "wǔ", italiano: "Cinque"},
        {hanzi: "六", pinyin: "liù", italiano: "Sei"},
        {hanzi: "七", pinyin: "qī", italiano: "Sette"},
        {hanzi: "九", pinyin: "jiǔ", italiano: "Nove"},
        {hanzi: "十", pinyin: "shí", italiano: "Dieci"}
    ],
    5: [
        {hanzi: "吗", pinyin: "ma", italiano: "Part. Mod. Interrogat."},
        {hanzi: "谁", pinyin: "shuí/shéi", italiano: "Chi?"},
        {hanzi: "是", pinyin: "shì", italiano: "Essere (verbo)"}
    ],
    6: [
        {hanzi: "班", pinyin: "bān", italiano: "Classe"},
        {hanzi: "的", pinyin: "de", italiano: "Part.strutt. determ. Nom."},
        {hanzi: "都", pinyin: "dōu", italiano: "Tutti (avv.)"},
        {hanzi: "和", pinyin: "hé", italiano: "E, con (cong.)"},
        {hanzi: "呢", pinyin: "ne", italiano: "(Part. mod.) e…? E per quanto riguarda…?"},
        {hanzi: "朋友", pinyin: "péngyou", italiano: "Amico/a"},
        {hanzi: "人", pinyin: "rén", italiano: "Uomo, persona"},
        {hanzi: "同学", pinyin: "tóngxué", italiano: "Compagno (di studio)"},
        {hanzi: "也", pinyin: "yě", italiano: "Anche (avv.)"},
        {hanzi: "德语", pinyin: "Déyǔ", italiano: "Lingua tedesca"},
        {hanzi: "法语", pinyin: "Fǎyǔ", italiano: "Lingua francese"},
        {hanzi: "日语", pinyin: "Rìyǔ", italiano: "Lingua giapponese"},
        {hanzi: "意大利语", pinyin: "Yìdàlìyǔ", italiano: "Lingua italiana"},
        {hanzi: "英语", pinyin: "Yīngyǔ", italiano: "Lingua inglese"},
        {hanzi: "雨", pinyin: "yǔ", italiano: "Pioggia"},
        {hanzi: "北京", pinyin: "Běijīng", italiano: "Pechino"},
        {hanzi: "罗马", pinyin: "Luómǎ", italiano: "Roma"},
        {hanzi: "米兰", pinyin: "Mǐlán", italiano: "Milano"}
    ],
    7: [
        {hanzi: "吧", pinyin: "ba", italiano: "Part. Finale (…, vero?)"},
        {hanzi: "大学", pinyin: "dàxué", italiano: "Università"},
        {hanzi: "对", pinyin: "duì", italiano: "Giusto, esatto"},
        {hanzi: "贵", pinyin: "guì", italiano: "Caro, prezioso"},
        {hanzi: "国", pinyin: "guó", italiano: "Paese, nazione"},
        {hanzi: "叫", pinyin: "jiào", italiano: "Chiamare, chiamarsi"},
        {hanzi: "留学生", pinyin: "liúxuéshēng", italiano: "Studente residente all’estero"},
        {hanzi: "名字", pinyin: "míngzi", italiano: "Nome (di persona)"},
        {hanzi: "哪", pinyin: "nǎ", italiano: "Quale? (pron. interr.)"},
        {hanzi: "哪儿", pinyin: "nǎr", italiano: "Dove? (pron. interr.)"},
        {hanzi: "您", pinyin: "nín", italiano: "Lei (forma di cortesia)"},
        {hanzi: "什么", pinyin: "shénme", italiano: "Che, che cosa"},
        {hanzi: "问", pinyin: "wèn", italiano: "Chiedere, domandare"},
        {hanzi: "文学", pinyin: "wénxué", italiano: "Letteratura"},
        {hanzi: "姓", pinyin: "xìng", italiano: "Cognome, fare di cognome"},
        {hanzi: "法国", pinyin: "Fǎguó", italiano: "Francia"},
        {hanzi: "意大利", pinyin: "Yìdàlì", italiano: "Italia"},
        {hanzi: "中国", pinyin: "Zhōngguó", italiano: "Cina"},
        {hanzi: "德国", pinyin: "Déguó", italiano: "Germania"},
        {hanzi: "俄国", pinyin: "Éguó", italiano: "Russia"},
        {hanzi: "美国", pinyin: "Měiguó", italiano: "Stati Uniti"},
        {hanzi: "日本", pinyin: "Rìběn", italiano: "Giappone"},
        {hanzi: "西班牙", pinyin: "Xībānyá", italiano: "Spagna"},
        {hanzi: "英国", pinyin: "Yīngguó", italiano: "Regno Unito"}
    ],
    8: [
        {hanzi: "爱好", pinyin: "àihào", italiano: "Hobby, interesse"},
        {hanzi: "常/常常", pinyin: "cháng", italiano: "Spesso"},
        {hanzi: "电话", pinyin: "diànhuà", italiano: "Telefono"},
        {hanzi: "电影", pinyin: "diànyǐng", italiano: "Film"},
        {hanzi: "多少", pinyin: "duōshǎo", italiano: "Quanto? Quanti?"},
        {hanzi: "号码", pinyin: "hàomǎ", italiano: "Numero"},
        {hanzi: "很", pinyin: "hěn", italiano: "Molto"},
        {hanzi: "看", pinyin: "kàn", italiano: "Guardare, leggere"},
        {hanzi: "上网", pinyin: "shàngwǎng", italiano: "Navigare in rete"},
        {hanzi: "少", pinyin: "shǎo", italiano: "Pochi"},
        {hanzi: "手机", pinyin: "shǒujī", italiano: "Telefono cellulare"},
        {hanzi: "书", pinyin: "shū", italiano: "Libro"},
        {hanzi: "跳舞", pinyin: "tiàowǔ", italiano: "Ballare"},
        {hanzi: "听", pinyin: "tīng", italiano: "Ascoltare"},
        {hanzi: "喜欢", pinyin: "xǐhuan", italiano: "Piacere (verbo)"},
        {hanzi: "音乐", pinyin: "yīnyuè", italiano: "Musica"},
        {hanzi: "唱歌", pinyin: "chànggē", italiano: "Cantare"},
        {hanzi: "广东话", pinyin: "Guǎngdōnghuà", italiano: "Cantonese (dialetto)"},
        {hanzi: "上海", pinyin: "Shànghǎi", italiano: "Shanghai"},
        {hanzi: "电视", pinyin: "Diànshì", italiano: "Televisione"},
        {hanzi: "普通话", pinyin: "pǔtōnghuà", italiano: "Lingua comune/standard"}
    ],
    9: [
        {hanzi: "词典", pinyin: "cídiǎn", italiano: "Dizionario"},
        {hanzi: "回", pinyin: "huí", italiano: "Tornare"},
        {hanzi: "家", pinyin: "jiā", italiano: "Casa, famiglia"},
        {hanzi: "今天", pinyin: "jīntiān", italiano: "Oggi"},
        {hanzi: "买", pinyin: "mǎi", italiano: "Comprare"},
        {hanzi: "明天", pinyin: "míngtiān", italiano: "Domani"},
        {hanzi: "男", pinyin: "nán", italiano: "Maschile"},
        {hanzi: "去", pinyin: "qù", italiano: "Andare"},
        {hanzi: "书店", pinyin: "shūdiàn", italiano: "Libreria (negozio)"},
        {hanzi: "晚上", pinyin: "wǎnshang", italiano: "Sera"},
        {hanzi: "行", pinyin: "xíng", italiano: "Andar bene"},
        {hanzi: "一起", pinyin: "yìqǐ", italiano: "Insieme"},
        {hanzi: "咱们", pinyin: "zánmen", italiano: "Noi (inclusi parl. e interl.)"},
        {hanzi: "中文", pinyin: "zhōngwén", italiano: "Lingua cinese (scritta)"},
        {hanzi: "东西", pinyin: "dōngxi", italiano: "Cosa, oggetto"},
        {hanzi: "来", pinyin: "lái", italiano: "Venire"},
        {hanzi: "商店", pinyin: "shāngdiàn", italiano: "Negozio"},
        {hanzi: "上午", pinyin: "shàngwǔ", italiano: "Mattina"},
        {hanzi: "下午", pinyin: "xiàwǔ", italiano: "Pomeriggio"},
        {hanzi: "早上", pinyin: "zǎoshang", italiano: "Mattina presto (fino alle 9 circa)"},
        {hanzi: "中午", pinyin: "zhōngwǔ", italiano: "Mezzogiorno e ore intorno al mezzogiorno"}
    ],
    10: [
        {hanzi: "等", pinyin: "děng", italiano: "Aspettare"},
        {hanzi: "教室", pinyin: "jiàoshì", italiano: "Aula"},
        {hanzi: "肯定", pinyin: "kěndìng", italiano: "Certamente, sicuramente"},
        {hanzi: "可能", pinyin: "kěnéng", italiano: "Forse"},
        {hanzi: "没", pinyin: "méi", italiano: "Negazione del verbo 有"},
        {hanzi: "拿", pinyin: "ná", italiano: "Prendere"},
        {hanzi: "那儿", pinyin: "nàr", italiano: "Lì, là"},
        {hanzi: "事", pinyin: "shì", italiano: "Cosa, faccenda, affare"},
        {hanzi: "图书馆", pinyin: "túshūguǎn", italiano: "Biblioteca"},
        {hanzi: "一下儿", pinyin: "yíxiàr", italiano: "Un po’, un attimo"},
        {hanzi: "用", pinyin: "yòng", italiano: "Usare"},
        {hanzi: "有", pinyin: "yǒu", italiano: "Avere, esserci"},
        {hanzi: "在", pinyin: "zài", italiano: "Essere in, in"},
        {hanzi: "这儿", pinyin: "zhèr", italiano: "Qui"},
        {hanzi: "只", pinyin: "zhǐ", italiano: "Soltanto, solo, solamente"},
        {hanzi: "知道", pinyin: "zhīdào", italiano: "Sapere"},
        {hanzi: "不客气", pinyin: "bú kèqi", italiano: "Prego (per rispondere a chi ringrazia)"}
    ],
    11: [
        {hanzi: "本", pinyin: "běn", italiano: "Classif. per oggetti in volume"},
        {hanzi: "本子", pinyin: "běnzi", italiano: "Quaderno"},
        {hanzi: "笔", pinyin: "bǐ", italiano: "Penna, matita"},
        {hanzi: "别的", pinyin: "biéde", italiano: "Altro, altri"},
        {hanzi: "磁带", pinyin: "cídài", italiano: "Audiocassetta"},
        {hanzi: "个", pinyin: "ge", italiano: "Classificatore generico per cose, persone e concetti astratti"},
        {hanzi: "光盘", pinyin: "guāngpán", italiano: "CD (compact disc)"},
        {hanzi: "还", pinyin: "hái", italiano: "Ancora, anche"},
        {hanzi: "还是", pinyin: "háishì", italiano: "Oppure (in frasi interrogative)"},
        {hanzi: "或者", pinyin: "huòzhě", italiano: "Oppure (in frasi affermative)"},
        {hanzi: "几", pinyin: "jǐ", italiano: "Quanti? Qualche, alcuni (per quantità da 1 a 10)"},
        {hanzi: "两", pinyin: "liǎng", italiano: "Due (per indicare quantità, non nella numerazione)"},
        {hanzi: "那", pinyin: "nà", italiano: "Quello"},
        {hanzi: "铅笔", pinyin: "qiānbǐ", italiano: "Matita"},
        {hanzi: "随便", pinyin: "suíbiàn", italiano: "Informale, libero"},
        {hanzi: "先生", pinyin: "xiānsheng", italiano: "Signore"},
        {hanzi: "些", pinyin: "xiē", italiano: "Usato dopo i dimostr. per indicare il plurale (alcuni)"},
        {hanzi: "要", pinyin: "yào", italiano: "Volere"},
        {hanzi: "张", pinyin: "zhāng", italiano: "Classif. per oggetti piatti e relativamente sottili"},
        {hanzi: "这", pinyin: "zhè", italiano: "Questo"},
        {hanzi: "支/枝", pinyin: "zhī", italiano: "Class. per oggetti a forma di bastoncino (es. penne)"},
        {hanzi: "种", pinyin: "zhǒng", italiano: "Class.: genere, tipo; anche class. per concetti astratti"},
        {hanzi: "杯", pinyin: "bēi", italiano: "Class.: tazza di, bicchiere di"}
    ],
    12: [
        {hanzi: "茶", pinyin: "chá", italiano: "Tè"},
        {hanzi: "但是", pinyin: "dànshì", italiano: "Ma"},
        {hanzi: "一点儿", pinyin: "yìdiǎnr", italiano: "Un po’"},
        {hanzi: "点心", pinyin: "diǎnxīn", italiano: "Spuntino (dim-sum)"},
        {hanzi: "读(书)", pinyin: "dú(shū)", italiano: "Leggere"},
        {hanzi: "喝", pinyin: "hē", italiano: "Bere"},
        {hanzi: "会", pinyin: "huì", italiano: "Saper fare, essere capace di (ausiliare modale)"},
        {hanzi: "酒吧", pinyin: "jiǔbā", italiano: "Bar"},
        {hanzi: "咖啡", pinyin: "kāfēi", italiano: "Caffè"},
        {hanzi: "开玩笑", pinyin: "kāi wánxiào", italiano: "Scherzare"},
        {hanzi: "可以", pinyin: "kěyǐ", italiano: "Potere (ausiliare modale)"},
        {hanzi: "块", pinyin: "kuài", italiano: "Pezzo, fetta (class.)"},
        {hanzi: "能", pinyin: "néng", italiano: "Potere, essere in grado di"},
        {hanzi: "啤酒", pinyin: "píjiǔ", italiano: "Birra"},
        {hanzi: "请客", pinyin: "qǐngkè", italiano: "Offrire, invitare qualcuno a consumare un pasto"},
        {hanzi: "勺儿", pinyin: "sháor", italiano: "Cucchiaio (sost. e class.)"},
        {hanzi: "说", pinyin: "shuō", italiano: "Parlare, dire"},
        {hanzi: "糖", pinyin: "táng", italiano: "Zucchero"},
        {hanzi: "晚会", pinyin: "wǎnhuì", italiano: "Festa (serale)"},
        {hanzi: "为什么", pinyin: "wèishénme", italiano: "Perché?"},
        {hanzi: "想", pinyin: "xiǎng", italiano: "Desiderare, volere (ausiliare modale)"},
        {hanzi: "写", pinyin: "xiě", italiano: "Scrivere"},
        {hanzi: "因为", pinyin: "yīnwèi", italiano: "Perché"},
        {hanzi: "怎么", pinyin: "zěnme", italiano: "Come, perché, come mai"},
        {hanzi: "走", pinyin: "zǒu", italiano: "Camminare, andar via"},
        {hanzi: "吃(饭)", pinyin: "chī(fàn)", italiano: "Mangiare"},
        {hanzi: "开车", pinyin: "kāichē", italiano: "Guidare"},
        {hanzi: "可乐", pinyin: "kělè", italiano: "Coca-cola"},
        {hanzi: "面包", pinyin: "miànbāo", italiano: "Pane"},
        {hanzi: "面条", pinyin: "miàntiáo", italiano: "Spaghetti"},
        {hanzi: "牛奶", pinyin: "niúnǎi", italiano: "Latte (vaccino)"},
        {hanzi: "水", pinyin: "shuǐ", italiano: "Acqua"}
    ],
    13: [
        {hanzi: "傲", pinyin: "ào", italiano: "Orgoglioso"},
        {hanzi: "别", pinyin: "bié", italiano: "Non, imperativo negativo"},
        {hanzi: "比较", pinyin: "bǐjiào", italiano: "Abbastanza"},
        {hanzi: "不错", pinyin: "búcuò", italiano: "Non male, discreto"},
        {hanzi: "聪明", pinyin: "cōngming", italiano: "Intelligente"},
        {hanzi: "粗心", pinyin: "cūxīn", italiano: "Negligente, trascurato"},
        {hanzi: "高兴", pinyin: "gāoxìng", italiano: "Felice, contento"},
        {hanzi: "很", pinyin: "hěn", italiano: "Molto"},
        {hanzi: "交", pinyin: "jiāo", italiano: "Stringere, fare (un’amicizia)"},
        {hanzi: "觉得", pinyin: "juéde", italiano: "Sentire, pensare"},
        {hanzi: "开朗", pinyin: "kāilǎng", italiano: "Aperto, allegro"},
        {hanzi: "酷", pinyin: "kù", italiano: "Forte, fantastico (per mostrare apprezzamento)"},
        {hanzi: "懒", pinyin: "lǎn", italiano: "Pigro"},
        {hanzi: "浪漫", pinyin: "làngmàn", italiano: "Romantico"},
        {hanzi: "忙", pinyin: "máng", italiano: "Impegnato, occupato"},
        {hanzi: "漂亮", pinyin: "piàoliang", italiano: "Bello"},
        {hanzi: "热情", pinyin: "rèqíng", italiano: "Caloroso, affettuoso, fervido"},
        {hanzi: "时候", pinyin: "shíhou", italiano: "Tempo, momento"},
        {hanzi: "喂", pinyin: "wèi", italiano: "Ehi, pronto"},
        {hanzi: "性格", pinyin: "xìnggé", italiano: "Carattere (di una persona)"},
        {hanzi: "意思", pinyin: "yìsi", italiano: "Significato, senso"},
        {hanzi: "这么", pinyin: "zhème", italiano: "Così"},
        {hanzi: "怎么样", pinyin: "zěnmeyàng", italiano: "Come…? Come va?"},
        {hanzi: "笨", pinyin: "bèn", italiano: "Stupido, sciocco"},
        {hanzi: "坏", pinyin: "huài", italiano: "Cattivo"},
        {hanzi: "腼腆", pinyin: "miǎntiǎn", italiano: "Timido"},
        {hanzi: "难", pinyin: "nán", italiano: "Difficile"},
        {hanzi: "努力", pinyin: "nǔlì", italiano: "Diligente"},
        {hanzi: "勤奋", pinyin: "qínfèn", italiano: "Diligente"},
        {hanzi: "认真", pinyin: "rènzhēn", italiano: "Serio, preciso"},
        {hanzi: "容易", pinyin: "róngyì", italiano: "Facile"},
        {hanzi: "现实", pinyin: "xiànshí", italiano: "Realista"}
    ],
    14: [
        {hanzi: "猜", pinyin: "cāi", italiano: "Indovinare"},
        {hanzi: "出生", pinyin: "chūshēng", italiano: "Nascere"},
        {hanzi: "大夫", pinyin: "dàifu", italiano: "Medico"},
        {hanzi: "弟弟", pinyin: "dìdi", italiano: "Fratello minore"},
        {hanzi: "哥哥", pinyin: "gēge", italiano: "Fratello maggiore"},
        {hanzi: "公司", pinyin: "gōngsī", italiano: "Ditta, azienda"},
        {hanzi: "工作", pinyin: "gōngzuò", italiano: "Lavoro, lavorare"},
        {hanzi: "关系", pinyin: "guānxi", italiano: "Rapporto, relazione, legame"},
        {hanzi: "号", pinyin: "hào", italiano: "Giorno (del mese)"},
        {hanzi: "欢迎", pinyin: "huānyíng", italiano: "Dare il benvenuto"},
        {hanzi: "介绍", pinyin: "jièshào", italiano: "Presentare"},
        {hanzi: "进", pinyin: "jìn", italiano: "Entrare"},
        {hanzi: "今年", pinyin: "jīnnián", italiano: "Quest’anno"},
        {hanzi: "口", pinyin: "kǒu", italiano: "Class. per membri di famiglia"},
        {hanzi: "妹妹", pinyin: "mèimei", italiano: "Sorella minore"},
        {hanzi: "奶奶", pinyin: "nǎinai", italiano: "Nonna paterna, appell. rispettoso per donna anziana"},
        {hanzi: "年", pinyin: "nián", italiano: "Anno"},
        {hanzi: "年级", pinyin: "niánjí", italiano: "Grado, classe (divisioni all’interno di un ciclo scol.)"},
        {hanzi: "牛", pinyin: "niú", italiano: "Bovino (vacca, bue)"},
        {hanzi: "生日", pinyin: "shēngrì", italiano: "Compleanno"},
        {hanzi: "身体", pinyin: "shēntǐ", italiano: "Salute, corpo"},
        {hanzi: "属", pinyin: "shǔ", italiano: "Appartenere, essere nato nell’anno del…"},
        {hanzi: "岁", pinyin: "suì", italiano: "Anno (d’età)"},
        {hanzi: "岁数", pinyin: "suìshù", italiano: "Età"},
        {hanzi: "像", pinyin: "xiàng", italiano: "Sembrare, somigliare"},
        {hanzi: "小伙子", pinyin: "xiǎohuǒzi", italiano: "Ragazzo, giovane"},
        {hanzi: "小学", pinyin: "xiǎoxué", italiano: "Scuola elementare"},
        {hanzi: "月", pinyin: "yuè", italiano: "Mese"},
        {hanzi: "在", pinyin: "zài", italiano: "Stare, essere in, (prep.) in"},
        {hanzi: "真", pinyin: "zhēn", italiano: "Vero, autentico; davvero, veramente"},
        {hanzi: "做", pinyin: "zuò", italiano: "Fare, fabbricare, svolgere (un lavoro)"},
        {hanzi: "法律", pinyin: "fǎlǜ", italiano: "Legge"},
        {hanzi: "姐姐", pinyin: "jiějie", italiano: "Sorella maggiore"},
        {hanzi: "经理", pinyin: "jīnglǐ", italiano: "Dirigere, direttore, manager"},
        {hanzi: "律师", pinyin: "lǜshī", italiano: "Avvocato"},
        {hanzi: "太太", pinyin: "tàitai", italiano: "Signora, moglie"},
        {hanzi: "医院", pinyin: "yīyuàn", italiano: "Ospedale"},
        {hanzi: "职员", pinyin: "zhíyuán", italiano: "Impiegato"},
        {hanzi: "中学", pinyin: "zhōngxué", italiano: "Scuola media inferiore"},
        {hanzi: "老鼠", pinyin: "lǎoshǔ", italiano: "Topo"},
        {hanzi: "牛", pinyin: "niú", italiano: "Bue"},
        {hanzi: "老虎", pinyin: "lǎohǔ", italiano: "Tigre"},
        {hanzi: "兔子", pinyin: "tùzi", italiano: "Coniglio"},
        {hanzi: "龙", pinyin: "lóng", italiano: "Drago"},
        {hanzi: "蛇", pinyin: "shé", italiano: "Serpente"},
        {hanzi: "马", pinyin: "mǎ", italiano: "Cavallo"},
        {hanzi: "羊", pinyin: "yáng", italiano: "Pecora"},
        {hanzi: "猴", pinyin: "hóu", italiano: "Scimmia"},
        {hanzi: "鸡", pinyin: "jī", italiano: "Gallo"},
        {hanzi: "狗", pinyin: "gǒu", italiano: "Cane"},
        {hanzi: "猪", pinyin: "zhū", italiano: "Maiale"}
    ],
    15: [
        {hanzi: "比赛", pinyin: "bǐsài", italiano: "Gareggiare, gara, competizione"},
        {hanzi: "车", pinyin: "chē", italiano: "Veicolo (general. morfema legato)"},
        {hanzi: "吹牛", pinyin: "chuīniú", italiano: "Vantarsi, millantare"},
        {hanzi: "当然", pinyin: "dāngrán", italiano: "Certamente, naturalmente"},
        {hanzi: "队", pinyin: "duì", italiano: "Riga, fila; squadra"},
        {hanzi: "对", pinyin: "duì", italiano: "(prep.) Nei confronti di"},
        {hanzi: "感", pinyin: "gǎn", italiano: "Sentire, provare (sempre seguito da un complem.)"},
        {hanzi: "跟", pinyin: "gēn", italiano: "(prep.) con; seguire"},
        {hanzi: "火车", pinyin: "huóchē", italiano: "Treno"},
        {hanzi: "开", pinyin: "kāi", italiano: "Guidare"},
        {hanzi: "路", pinyin: "lù", italiano: "Strada (general. morfema legato)"},
        {hanzi: "乱", pinyin: "luàn", italiano: "Disordinato, confuso"},
        {hanzi: "迷", pinyin: "mí", italiano: "Patito, entusiasta"},
        {hanzi: "票", pinyin: "piào", italiano: "Biglietto"},
        {hanzi: "骑", pinyin: "qí", italiano: "Cavalcare; andare in (bici, moto ecc.)"},
        {hanzi: "球", pinyin: "qiú", italiano: "Palla"},
        {hanzi: "(足球)迷", pinyin: "(zúqiú)mí", italiano: "Tifoso (di calcio)"},
        {hanzi: "球赛", pinyin: "qiúsài", italiano: "Partita (di sport con la palla)"},
        {hanzi: "热闹", pinyin: "rènao", italiano: "Vivace, movimentato"},
        {hanzi: "赛", pinyin: "sài", italiano: "Gara, competizione (generalm. morf. legato)"},
        {hanzi: "输", pinyin: "shū", italiano: "Perdere"},
        {hanzi: "体育场", pinyin: "tǐyùchǎng", italiano: "Stadio"},
        {hanzi: "小心", pinyin: "xiǎoxīn", italiano: "Fare attenzione, essere prudente"},
        {hanzi: "兴趣", pinyin: "xìngqu", italiano: "Interesse"},
        {hanzi: "要是", pinyin: "yàoshi", italiano: "Se"},
        {hanzi: "眼镜", pinyin: "yǎnjìng", italiano: "Occhiali"},
        {hanzi: "一定", pinyin: "yídìng", italiano: "Certamente"},
        {hanzi: "应该", pinyin: "yīnggāi", italiano: "Dovere (condiz.)"},
        {hanzi: "自行车", pinyin: "zìxíngchē", italiano: "Bicicletta"},
        {hanzi: "走路", pinyin: "zǒulù", italiano: "Camminare"},
        {hanzi: "坐", pinyin: "zuò", italiano: "Sedere, viaggiare su un veicolo (treno, auto ecc.)"},
        {hanzi: "足球", pinyin: "zúqiú", italiano: "Gioco del calcio"},
        {hanzi: "地铁", pinyin: "dìtiě", italiano: "Metropolitana"},
        {hanzi: "飞机", pinyin: "fēijī", italiano: "Aereo"},
        {hanzi: "公共汽车", pinyin: "gōnggòngqìchē", italiano: "Autobus"},
        {hanzi: "辆", pinyin: "liǎng", italiano: "Class. per bus, bicicletta, moto, auto"},
        {hanzi: "踢(足球)", pinyin: "tī(zúqiú)", italiano: "Calciare, giocare (a calcio)"},
        {hanzi: "赢", pinyin: "yíng", italiano: "Vincere"}
    ],
    16: [
        {hanzi: "半", pinyin: "bàn", italiano: "Metà, mezzo"},
        {hanzi: "差", pinyin: "chà", italiano: "Mancare"},
        {hanzi: "从", pinyin: "cóng", italiano: "Da (moto da luogo)"},
        {hanzi: "打", pinyin: "dǎ", italiano: "Colpire, battere; prendere (un taxi)"},
        {hanzi: "大概", pinyin: "dàgài", italiano: "Probabilmente"},
        {hanzi: "到", pinyin: "dào", italiano: "Arrivare; (prep.) a, per (moto a luogo)"},
        {hanzi: "导游", pinyin: "dǎoyóu", italiano: "Guida turistica"},
        {hanzi: "当", pinyin: "dāng", italiano: "Svolgere (un’attività)"},
        {hanzi: "点", pinyin: "diǎn", italiano: "Unità per indicare le ore nel tempo cronologico"},
        {hanzi: "飞机场", pinyin: "fēijīchǎng", italiano: "Aeroporto"},
        {hanzi: "分", pinyin: "fēn", italiano: "Minuto primo"},
        {hanzi: "坏", pinyin: "huài", italiano: "Cattivo, malvagio"},
        {hanzi: "接", pinyin: "jiē", italiano: "Incontrare (qualcuno in arrivo), accogliere"},
        {hanzi: "开始", pinyin: "kāishǐ", italiano: "Cominciare"},
        {hanzi: "刻", pinyin: "kè", italiano: "Quarto d’ora"},
        {hanzi: "空儿", pinyin: "kòngr", italiano: "Tempo libero, spazio libero"},
        {hanzi: "口语", pinyin: "kǒuyǔ", italiano: "Lingua parlata"},
        {hanzi: "快", pinyin: "kuài", italiano: "Veloce, velocemente, rapido, rapidamente"},
        {hanzi: "钱", pinyin: "qián", italiano: "Soldi, denaro"},
        {hanzi: "然后", pinyin: "ránhòu", italiano: "Dopo, in seguito"},
        {hanzi: "时间", pinyin: "shíjiān", italiano: "Tempo"},
        {hanzi: "玩儿", pinyin: "wánr", italiano: "Giocare, divertirsi, svagarsi, passare il tempo"},
        {hanzi: "问题", pinyin: "wèntí", italiano: "Problema, domanda"},
        {hanzi: "小时", pinyin: "xiǎoshí", italiano: "Ora (nel senso di durata)"},
        {hanzi: "先", pinyin: "xiān", italiano: "Prima (avverbio)"},
        {hanzi: "星期", pinyin: "xīngqī", italiano: "Settimana"},
        {hanzi: "站", pinyin: "zhàn", italiano: "Stazione, fermata, stare in piedi"},
        {hanzi: "周", pinyin: "zhōu", italiano: "Settimana"},
        {hanzi: "周末", pinyin: "zhōumò", italiano: "Fine settimana"},
        {hanzi: "最", pinyin: "zuì", italiano: "Più (avv. per superlativo relativo)"},
        {hanzi: "出租汽车", pinyin: "chūzūqìchē", italiano: "Taxi"},
        {hanzi: "节", pinyin: "jié", italiano: "Class. per ore di lezione"},
        {hanzi: "下课", pinyin: "xiàkè", italiano: "Finire la lezione"},
        {hanzi: "语法", pinyin: "yǔfǎ", italiano: "Grammatica"},
        {hanzi: "钟", pinyin: "zhōng", italiano: "Ora usato dopo le parole 分 e 刻"}
    ],
    17: [
        {hanzi: "报", pinyin: "bào", italiano: "Giornale"},
        {hanzi: "笔记本", pinyin: "bǐjìběn", italiano: "Quaderno per appunti"},
        {hanzi: "打算", pinyin: "dǎsuàn", italiano: "Avere intenzione di, programmare, intenzione"},
        {hanzi: "的时候", pinyin: "de shíhou", italiano: "Quando"},
        {hanzi: "得", pinyin: "děi", italiano: "Dovere (ausiliare modale)"},
        {hanzi: "电脑", pinyin: "diànnǎo", italiano: "Computer"},
        {hanzi: "笔记本电脑", pinyin: "bǐjìběn diànnǎo", italiano: "Computer portatile"},
        {hanzi: "二手", pinyin: "èrshǒu", italiano: "Di seconda mano"},
        {hanzi: "付", pinyin: "fù", italiano: "Affidare, pagare"},
        {hanzi: "辅导", pinyin: "fǔdǎo", italiano: "Dare ripetizioni"},
        {hanzi: "给", pinyin: "gěi", italiano: "Dare; a, per"},
        {hanzi: "过", pinyin: "guò", italiano: "Attraversare, percorrere, passare, trascorrere (tempo)"},
        {hanzi: "害怕", pinyin: "hàipà", italiano: "Temere, aver paura"},
        {hanzi: "还", pinyin: "huán", italiano: "Restituire"},
        {hanzi: "教书", pinyin: "jiāoshū", italiano: "Insegnare"},
        {hanzi: "借", pinyin: "jiè", italiano: "Prendere in prestito, prestare"},
        {hanzi: "论文", pinyin: "lùnwén", italiano: "Tesi, saggio"},
        {hanzi: "每", pinyin: "měi", italiano: "Ogni"},
        {hanzi: "这么", pinyin: "zhème", italiano: "Talmente, così"},
        {hanzi: "书法", pinyin: "shūfǎ", italiano: "Calligrafia"},
        {hanzi: "送", pinyin: "sòng", italiano: "Regalare, consegnare"},
        {hanzi: "台", pinyin: "tái", italiano: "Classificatore usato per apparecchi"},
        {hanzi: "忘", pinyin: "wàng", italiano: "Dimenticare"},
        {hanzi: "小气", pinyin: "xiǎoqì", italiano: "Avaro, tirchio"},
        {hanzi: "新", pinyin: "xīn", italiano: "Nuovo"},
        {hanzi: "这样", pinyin: "zhèyàng", italiano: "Così, in questo modo"},
        {hanzi: "自己", pinyin: "zìjǐ", italiano: "Sé stesso, da sé, proprio"},
        {hanzi: "发音", pinyin: "fāyīn", italiano: "Pronuncia"},
        {hanzi: "会话", pinyin: "huìhuà", italiano: "Conversazione"},
        {hanzi: "回答", pinyin: "huídá", italiano: "Rispondere"},
        {hanzi: "旧", pinyin: "jiù", italiano: "Vecchio"},
        {hanzi: "慷慨", pinyin: "kāngkǎi", italiano: "Impetuoso, generoso"},
        {hanzi: "听力", pinyin: "tīnglì", italiano: "Capacità di ascolto"}
    ],
    18: [
        {hanzi: "衬衫", pinyin: "chènshān", italiano: "Camicia"},
        {hanzi: "穿", pinyin: "chuān", italiano: "Indossare"},
        {hanzi: "肥", pinyin: "féi", italiano: "Largo, grasso (non per persone)"},
        {hanzi: "干", pinyin: "gàn", italiano: "Fare"},
        {hanzi: "逛", pinyin: "guàng", italiano: "Passeggiare, andare in giro"},
        {hanzi: "合适", pinyin: "héshì", italiano: "Adatto"},
        {hanzi: "红", pinyin: "hóng", italiano: "Rosso"},
        {hanzi: "件", pinyin: "jiàn", italiano: "Class. per capi di abbigliamento"},
        {hanzi: "减价", pinyin: "jiǎnjià", italiano: "Scontare il prezzo"},
        {hanzi: "裤子", pinyin: "kùzi", italiano: "Pantaloni"},
        {hanzi: "块", pinyin: "kuài", italiano: "Pezzo di (class.), usato colloquialmente per 'yuan'"},
        {hanzi: "蓝", pinyin: "lán", italiano: "Blu, azzurro"},
        {hanzi: "礼物", pinyin: "lǐwù", italiano: "Regalo"},
        {hanzi: "练习", pinyin: "liànxí", italiano: "Esercizio, esercitarsi"},
        {hanzi: "欧元", pinyin: "ōuyuán", italiano: "Euro"},
        {hanzi: "胖", pinyin: "pàng", italiano: "Grasso, paffuto"},
        {hanzi: "便宜", pinyin: "piányi", italiano: "A buon mercato, economico"},
        {hanzi: "浅", pinyin: "qiǎn", italiano: "Chiaro (di colore)"},
        {hanzi: "穷", pinyin: "qióng", italiano: "Povero"},
        {hanzi: "人民币", pinyin: "rénmínbì", italiano: "Moneta del popolo"},
        {hanzi: "试", pinyin: "shì", italiano: "Provare"},
        {hanzi: "瘦", pinyin: "shòu", italiano: "Magro, stretto (di vestiti)"},
        {hanzi: "售货员", pinyin: "shòuhuòyuán", italiano: "Commesso"},
        {hanzi: "算了", pinyin: "suàn le", italiano: "Basta, va bene"},
        {hanzi: "条", pinyin: "tiáo", italiano: "Class. per cose di forma lunga e stretta"},
        {hanzi: "颜色", pinyin: "yánsè", italiano: "Colore"},
        {hanzi: "样子", pinyin: "yàngzi", italiano: "Forma, aspetto"},
        {hanzi: "一点儿", pinyin: "yìdiǎnr", italiano: "Un po’"},
        {hanzi: "衣服", pinyin: "yīfu", italiano: "Vestito"},
        {hanzi: "一共", pinyin: "yígòng", italiano: "In tutto"},
        {hanzi: "正", pinyin: "zhèng", italiano: "Proprio, precisamente, avv. per azione in corso"},
        {hanzi: "正好", pinyin: "zhènghǎo", italiano: "Perfettamente, per coincidenza, proprio"},
        {hanzi: "白", pinyin: "bái", italiano: "Bianco"},
        {hanzi: "分", pinyin: "fēn", italiano: "Centesimo (di valuta monetaria)"},
        {hanzi: "服装", pinyin: "fúzhuāng", italiano: "Abbigliamento"},
        {hanzi: "黑", pinyin: "hēi", italiano: "Nero"},
        {hanzi: "黄", pinyin: "huáng", italiano: "Giallo"},
        {hanzi: "角", pinyin: "jiǎo", italiano: "Decimo di yuan"},
        {hanzi: "绿", pinyin: "lǜ", italiano: "Verde"},
        {hanzi: "毛", pinyin: "máo", italiano: "Decimo di yuan (colloquiale)"},
        {hanzi: "裙子", pinyin: "qúnzi", italiano: "Gonna"},
        {hanzi: "深", pinyin: "shēn", italiano: "Scuro (di colore), profondo"},
        {hanzi: "双", pinyin: "shuāng", italiano: "Paio (class.)"},
        {hanzi: "鞋", pinyin: "xié", italiano: "Scarpa"},
        {hanzi: "元", pinyin: "yuán", italiano: "Unità di valuta"}
    ],
    19: [
        {hanzi: "北", pinyin: "běi", italiano: "Nord"},
        {hanzi: "餐馆", pinyin: "cānguǎn", italiano: "Ristorante"},
        {hanzi: "超市", pinyin: "chāoshì", italiano: "Supermercato"},
        {hanzi: "电影院", pinyin: "diànyǐngyuàn", italiano: "Cinema"},
        {hanzi: "地图", pinyin: "dìtú", italiano: "Mappa, carta geografica"},
        {hanzi: "东", pinyin: "dōng", italiano: "Est"},
        {hanzi: "对面", pinyin: "duìmiàn", italiano: "Opposto, di fronte"},
        {hanzi: "拐", pinyin: "guǎi", italiano: "Girare, svoltare"},
        {hanzi: "过", pinyin: "guò", italiano: "Festeggiare"},
        {hanzi: "红绿灯", pinyin: "hónglǜdēng", italiano: "Semaforo"},
        {hanzi: "换", pinyin: "huàn", italiano: "Cambiare"},
        {hanzi: "后边", pinyin: "hòubian", italiano: "Dietro"},
        {hanzi: "近", pinyin: "jìn", italiano: "Vicino"},
        {hanzi: "就", pinyin: "jiù", italiano: "Proprio (avv.)"},
        {hanzi: "酒家", pinyin: "jiǔjiā", italiano: "Ristorante (usato nei nomi di ristorante)"},
        {hanzi: "快乐", pinyin: "kuàilè", italiano: "Gioioso, allegro"},
        {hanzi: "离", pinyin: "lí", italiano: "Da (per indicare distanza)"},
        {hanzi: "路口", pinyin: "lùkǒu", italiano: "Incrocio"},
        {hanzi: "米", pinyin: "mǐ", italiano: "Metro (class.)"},
        {hanzi: "南", pinyin: "nán", italiano: "Sud"},
        {hanzi: "门口", pinyin: "ménkǒu", italiano: "Ingresso"},
        {hanzi: "旁边", pinyin: "pángbiān", italiano: "Lato, a fianco di"},
        {hanzi: "市", pinyin: "shì", italiano: "Città, mercato"},
        {hanzi: "往", pinyin: "wǎng", italiano: "Verso, andare in direzione di"},
        {hanzi: "西", pinyin: "xī", italiano: "Ovest"},
        {hanzi: "线", pinyin: "xiàn", italiano: "Linea, percorso"},
        {hanzi: "一直", pinyin: "yìzhí", italiano: "Sempre, costantemente"},
        {hanzi: "右", pinyin: "yòu", italiano: "Destra"},
        {hanzi: "远", pinyin: "yuǎn", italiano: "Lontano"},
        {hanzi: "中心", pinyin: "zhōngxīn", italiano: "Centro"},
        {hanzi: "祝", pinyin: "zhù", italiano: "Augurare"},
        {hanzi: "桌子", pinyin: "zhuōzi", italiano: "Tavolo"},
        {hanzi: "左", pinyin: "zuǒ", italiano: "Sinistra"},
        {hanzi: "左右", pinyin: "zuǒyòu", italiano: "Circa"},
        {hanzi: "北边", pinyin: "běibian", italiano: "A settentrione"},
        {hanzi: "东边", pinyin: "dōngbian", italiano: "A oriente"},
        {hanzi: "公里", pinyin: "gōnglǐ", italiano: "Chilometro"},
        {hanzi: "里边", pinyin: "lǐbian", italiano: "Dentro"},
        {hanzi: "楼", pinyin: "lóu", italiano: "Edificio, palazzo"},
        {hanzi: "南边", pinyin: "nánbian", italiano: "A meridione"},
        {hanzi: "前边", pinyin: "qiánbian", italiano: "Davanti"},
        {hanzi: "上边", pinyin: "shàngbian", italiano: "Sopra"},
        {hanzi: "外边", pinyin: "wàibian", italiano: "Fuori"},
        {hanzi: "下边", pinyin: "xiàbian", italiano: "Sotto"},
        {hanzi: "西边", pinyin: "xībian", italiano: "A occidente"},
        {hanzi: "银行", pinyin: "yínháng", italiano: "Banca"},
        {hanzi: "右边", pinyin: "yòubian", italiano: "A destra"},
        {hanzi: "中间", pinyin: "zhōngjiān", italiano: "Al centro, in mezzo"},
        {hanzi: "左边", pinyin: "zuǒbian", italiano: "A sinistra"}
    ],
    20: [
        {hanzi: "白菜", pinyin: "báicài", italiano: "Cavolo cinese"},
        {hanzi: "米饭", pinyin: "mǐfàn", italiano: "Riso cotto"},
        {hanzi: "菜", pinyin: "cài", italiano: "Pietanza, piatto, verdura, cucina"},
        {hanzi: "菜单", pinyin: "càidān", italiano: "Menù"},
        {hanzi: "炒", pinyin: "chǎo", italiano: "Saltare in padella"},
        {hanzi: "炒面", pinyin: "chǎomiàn", italiano: "Spaghetti saltati in padella"},
        {hanzi: "窗户", pinyin: "chuānghu", italiano: "Finestra"},
        {hanzi: "春卷", pinyin: "chūnjuǎn", italiano: "Involtino primavera"},
        {hanzi: "次", pinyin: "cì", italiano: "Volta (class. verbale)"},
        {hanzi: "醋", pinyin: "cù", italiano: "Aceto"},
        {hanzi: "带", pinyin: "dài", italiano: "Portare"},
        {hanzi: "单", pinyin: "dān", italiano: "Elenco, lista, polizza"},
        {hanzi: "豆腐", pinyin: "dòufu", italiano: "Cagliata (formaggio) di soia"},
        {hanzi: "份", pinyin: "fèn", italiano: "Porzione"},
        {hanzi: "服务员", pinyin: "fúwùyuán", italiano: "Cameriere"},
        {hanzi: "好吃", pinyin: "hǎochī", italiano: "Buono (per le cose da mangiare)"},
        {hanzi: "叫", pinyin: "jiào", italiano: "Far fare a q.no"},
        {hanzi: "饺子", pinyin: "jiǎozi", italiano: "Raviolo"},
        {hanzi: "烤", pinyin: "kǎo", italiano: "Arrostire al forno"},
        {hanzi: "考试", pinyin: "kǎoshì", italiano: "Esame, sostenere un esame"},
        {hanzi: "筷子", pinyin: "kuàizi", italiano: "Bacchette"},
        {hanzi: "买单", pinyin: "mǎidān", italiano: "Chiedere il conto"},
        {hanzi: "面", pinyin: "miàn", italiano: "Pasta, spaghetti"},
        {hanzi: "瓶", pinyin: "píng", italiano: "Bottiglia (class.)"},
        {hanzi: "气", pinyin: "qì", italiano: "Gas"},
        {hanzi: "瓶子", pinyin: "píngzi", italiano: "Bottiglia (sost.)"},
        {hanzi: "让", pinyin: "ràng", italiano: "Consentire, far fare a q.no, permettere"},
        {hanzi: "水果", pinyin: "shuǐguǒ", italiano: "Frutta"},
        {hanzi: "素", pinyin: "sù", italiano: "Vegetale"},
        {hanzi: "糖醋", pinyin: "tángcù", italiano: "Agrodolce"},
        {hanzi: "甜点", pinyin: "tiándiǎn", italiano: "Dessert"},
        {hanzi: "碗", pinyin: "wǎn", italiano: "Ciotola (class.)"},
        {hanzi: "晚", pinyin: "wǎn", italiano: "Tardi"},
        {hanzi: "鸭", pinyin: "yā", italiano: "Anatra"},
        {hanzi: "鱼", pinyin: "yú", italiano: "Pesce"},
        {hanzi: "把", pinyin: "bǎ", italiano: "Class. per cose che si impugnano"},
        {hanzi: "叉子", pinyin: "chāzi", italiano: "Forchetta"},
        {hanzi: "橙汁", pinyin: "chéngzhī", italiano: "Spremuta d’arancia"},
        {hanzi: "刀子", pinyin: "dāozi", italiano: "Coltello"},
        {hanzi: "果汁", pinyin: "guǒzhī", italiano: "Succo di frutta"},
        {hanzi: "鸡", pinyin: "jī", italiano: "Pollo"},
        {hanzi: "酱油", pinyin: "jiàngyóu", italiano: "Salsa di soia"},
        {hanzi: "苦", pinyin: "kǔ", italiano: "Amaro"},
        {hanzi: "辣", pinyin: "là", italiano: "Piccante"},
        {hanzi: "苹果汁", pinyin: "píngguǒzhī", italiano: "Succo di mela"},
        {hanzi: "葡萄酒", pinyin: "pútáojiǔ", italiano: "Vino d’uva"},
        {hanzi: "酸", pinyin: "suān", italiano: "Agro, aspro"},
        {hanzi: "甜", pinyin: "tián", italiano: "Dolce (agg.)"},
        {hanzi: "咸", pinyin: "xián", italiano: "Salato"},
        {hanzi: "汁", pinyin: "zhī", italiano: "Succo, spremuta"}
    ],
    21: [
        {hanzi: "爱", pinyin: "ài", italiano: "Amare, essere appassionato di"},
        {hanzi: "别提了", pinyin: "bié tí le", italiano: "Non ne parliamo"},
        {hanzi: "笔试", pinyin: "bǐshì", italiano: "Esame scritto"},
        {hanzi: "部分", pinyin: "bùfēn", italiano: "Parte"},
        {hanzi: "补考", pinyin: "bǔkǎo", italiano: "Ripetere un esame"},
        {hanzi: "担心", pinyin: "dānxīn", italiano: "Preoccuparsi"},
        {hanzi: "得", pinyin: "de", italiano: "Particella per il complem. di grado"},
        {hanzi: "得", pinyin: "dé", italiano: "Ottenere"},
        {hanzi: "翻译", pinyin: "fānyì", italiano: "Tradurre, interprete"},
        {hanzi: "分", pinyin: "fēn", italiano: "Punto, voto (scolastico)"},
        {hanzi: "更", pinyin: "gèng", italiano: "Ancora più, di più, ulteriormente"},
        {hanzi: "嫉妒", pinyin: "jídù", italiano: "Invidiare, essere geloso"},
        {hanzi: "及格", pinyin: "jígé", italiano: "Superare (un esame)"},
        {hanzi: "考", pinyin: "kǎo", italiano: "Sostenere un esame, esaminare"},
        {hanzi: "考题", pinyin: "kǎotí", italiano: "Domande d’esame"},
        {hanzi: "流利", pinyin: "liúlì", italiano: "Fluente"},
        {hanzi: "内容", pinyin: "nèiróng", italiano: "Contenuto"},
        {hanzi: "怕", pinyin: "pà", italiano: "Temere, aver paura"},
        {hanzi: "平时", pinyin: "píngshí", italiano: "Solitamente, normalmente"},
        {hanzi: "起床", pinyin: "qǐchuáng", italiano: "Alzarsi dal letto"},
        {hanzi: "书呆子", pinyin: "shūdāizi", italiano: "Topo di biblioteca, secchione"},
        {hanzi: "睡觉", pinyin: "shuìjiào", italiano: "Dormire"},
        {hanzi: "虽然", pinyin: "suīrán", italiano: "Sebbene, malgrado"},
        {hanzi: "讨厌", pinyin: "tǎoyàn", italiano: "Provare antipatia per, detestare, antipatico"},
        {hanzi: "晚", pinyin: "wǎn", italiano: "Tardi"},
        {hanzi: "为了", pinyin: "wèile", italiano: "Per, al fine di"},
        {hanzi: "文化", pinyin: "wénhuà", italiano: "Cultura"},
        {hanzi: "语言", pinyin: "yǔyán", italiano: "Lingua"},
        {hanzi: "早", pinyin: "zǎo", italiano: "Presto"},
        {hanzi: "主要", pinyin: "zhǔyào", italiano: "Principalmente, principale, primario"},
        {hanzi: "准", pinyin: "zhǔn", italiano: "Esatto, preciso"},
        {hanzi: "准备", pinyin: "zhǔnbèi", italiano: "Preparare"}
    ],
    22: [
        {hanzi: "办", pinyin: "bàn", italiano: "Fare, sbrigare"},
        {hanzi: "帮助", pinyin: "bāngzhù", italiano: "Aiutare, aiuto"},
        {hanzi: "大使馆", pinyin: "dàshǐguǎn", italiano: "Ambasciata"},
        {hanzi: "发展", pinyin: "fāzhǎn", italiano: "Sviluppare, svilupparsi, sviluppo"},
        {hanzi: "搞", pinyin: "gǎo", italiano: "Fare, organizzare, essere impegnato in"},
        {hanzi: "画报", pinyin: "huàbào", italiano: "Rivista illustrata"},
        {hanzi: "活动", pinyin: "huódòng", italiano: "Attività"},
        {hanzi: "极了", pinyin: "jí", italiano: "Estremamente"},
        {hanzi: "紧张", pinyin: "jǐnzhāng", italiano: "Nervoso, teso"},
        {hanzi: "就", pinyin: "jiù", italiano: "Allora, quindi"},
        {hanzi: "举行", pinyin: "jǔxíng", italiano: "Svolgere"},
        {hanzi: "可爱", pinyin: "kě'ài", italiano: "Amabile, grazioso"},
        {hanzi: "可惜", pinyin: "kěxī", italiano: "È un peccato"},
        {hanzi: "了解", pinyin: "liǎojiě", italiano: "Capire, comprendere, comprensione"},
        {hanzi: "认识", pinyin: "rènshi", italiano: "Conoscere, riconoscere, conoscenza, comprensione"},
        {hanzi: "生活", pinyin: "shēnghuó", italiano: "Vita, vivere"},
        {hanzi: "特别", pinyin: "tèbié", italiano: "Particolarmente, particolare"},
        {hanzi: "图片", pinyin: "túpiàn", italiano: "Illustrazione, immagine"},
        {hanzi: "晚饭", pinyin: "wǎnfàn", italiano: "Cena"},
        {hanzi: "笑", pinyin: "xiào", italiano: "Ridere"},
        {hanzi: "以为", pinyin: "yǐwéi", italiano: "Pensare, ritenere"},
        {hanzi: "又", pinyin: "yòu", italiano: "Sia…, nuovamente"},
        {hanzi: "有意思", pinyin: "yǒuyìsi", italiano: "Interessante"},
        {hanzi: "杂志", pinyin: "zázhì", italiano: "Rivista"},
        {hanzi: "再", pinyin: "zài", italiano: "Ancora, di nuovo"},
        {hanzi: "展览", pinyin: "zhǎnlǎn", italiano: "Esposizione, mostra"},
        {hanzi: "找", pinyin: "zhǎo", italiano: "Cercare"},
        {hanzi: "只好", pinyin: "zhǐhǎo", italiano: "Essere costretti a, dovere, non potere fare altro che…"},
        {hanzi: "只是", pinyin: "zhǐshì", italiano: "Soltanto, solo che…"},
        {hanzi: "专门", pinyin: "zhuānmén", italiano: "Specialmente"},
        {hanzi: "最近", pinyin: "zuìjìn", italiano: "Recente, di recente"},
        {hanzi: "做客", pinyin: "zuòkè", italiano: "Essere ospite"}
    ],
    23: [
        {hanzi: "AA制", pinyin: "AAzhì", italiano: "Pagare per proprio conto"},
        {hanzi: "按时", pinyin: "ànshí", italiano: "Puntualmente"},
        {hanzi: "不要紧", pinyin: "bú yàojǐn", italiano: "Non preoccuparsi"},
        {hanzi: "要不然", pinyin: "yàobùrán", italiano: "Altrimenti"},
        {hanzi: "才", pinyin: "cái", italiano: "Soltanto, appena"},
        {hanzi: "吵架", pinyin: "chǎojià", italiano: "Litigare"},
        {hanzi: "成", pinyin: "chéng", italiano: "Diventare"},
        {hanzi: "吃醋", pinyin: "chīcù", italiano: "Essere geloso"},
        {hanzi: "迟到", pinyin: "chídào", italiano: "Fare tardi, ritardare"},
        {hanzi: "从来", pinyin: "cónglái", italiano: "Sempre (in frasi negative: mai)"},
        {hanzi: "公园", pinyin: "gōngyuán", italiano: "Parco"},
        {hanzi: "光", pinyin: "guāng", italiano: "Solamente"},
        {hanzi: "故意", pinyin: "gùyì", italiano: "Intenzionalmente"},
        {hanzi: "后来", pinyin: "hòulái", italiano: "In seguito"},
        {hanzi: "花", pinyin: "huā", italiano: "Spendere, fiore"},
        {hanzi: "见面", pinyin: "jiànmiàn", italiano: "Incontrarsi, vedersi"},
        {hanzi: "就", pinyin: "jiù", italiano: "Quindi, già"},
        {hanzi: "客气", pinyin: "kèqi", italiano: "Fare i complimenti, gentile, cortese"},
        {hanzi: "礼貌", pinyin: "lǐmào", italiano: "Educazione"},
        {hanzi: "门口", pinyin: "ménkǒu", italiano: "Porta, ingresso"},
        {hanzi: "前天", pinyin: "qiántiān", italiano: "L’altro ieri"},
        {hanzi: "入乡随俗", pinyin: "rù xiāng suí sú", italiano: "Adattarsi agli usi locali"},
        {hanzi: "生气", pinyin: "shēngqì", italiano: "Arrabbiarsi"},
        {hanzi: "习惯", pinyin: "xíguàn", italiano: "Abitudine, abituarsi"},
        {hanzi: "要紧", pinyin: "yàojǐn", italiano: "Importante, grave"},
        {hanzi: "也许", pinyin: "yěxǔ", italiano: "Essere probabile, forse, probabilmente"},
        {hanzi: "一般", pinyin: "yìbān", italiano: "Comune, usuale"},
        {hanzi: "已经", pinyin: "yǐjīng", italiano: "Già"},
        {hanzi: "原因", pinyin: "yuányīn", italiano: "Causa"},
        {hanzi: "约", pinyin: "yuē", italiano: "Accordarsi"},
        {hanzi: "约会", pinyin: "yuēhuì", italiano: "Appuntamento, prendere un appuntamento"},
        {hanzi: "再说", pinyin: "zàishuō", italiano: "Inoltre"},
        {hanzi: "重要", pinyin: "zhòngyào", italiano: "Importante"},
        {hanzi: "遵守", pinyin: "zūnshǒu", italiano: "Rispettare"},
        {hanzi: "规定", pinyin: "guīdìng", italiano: "Regolamento"}
    ],

    // ===== CAPITOLO 24 =====
    24: [
        {hanzi: "百分之", pinyin: "bǎifēnzhī", italiano: "Percentuale"},
        {hanzi: "比萨饼", pinyin: "bǐsàbǐng", italiano: "Pizza"},
        {hanzi: "博物馆", pinyin: "bówùguǎn", italiano: "Museo"},
        {hanzi: "不但...而且", pinyin: "bùdàn...érqiě", italiano: "Non solo... ma anche"},
        {hanzi: "参观", pinyin: "cānguǎn", italiano: "Visitare (un luogo)"},
        {hanzi: "成千上万", pinyin: "chéngqiān shàngwàn", italiano: "A migliaia"},
        {hanzi: "雕塑", pinyin: "diāosù", italiano: "Statua"},
        {hanzi: "地方", pinyin: "dìfang", italiano: "Luogo, posto"},
        {hanzi: "而", pinyin: "ér", italiano: "Anche, invece"},
        {hanzi: "方便", pinyin: "fāngbian", italiano: "Comodo"},
        {hanzi: "各", pinyin: "gè", italiano: "Ogni"},
        {hanzi: "古迹", pinyin: "gǔjì", italiano: "Vestigia storiche"},
        {hanzi: "过", pinyin: "guo", italiano: "Particella aspettuale per esperienza avuta"},
        {hanzi: "过奖", pinyin: "guòjiǎng", italiano: "Esagerare nei complimenti"},
        {hanzi: "绘画", pinyin: "huìhuà", italiano: "Dipinto"},
        {hanzi: "互相", pinyin: "hùxiāng", italiano: "Reciprocamente"},
        {hanzi: "精美", pinyin: "jīngměi", italiano: "Bello"},
        {hanzi: "进修", pinyin: "jìnxiū", italiano: "Perfezionarsi"},
        {hanzi: "留下", pinyin: "liúxià", italiano: "Lasciare"},
        {hanzi: "旅行", pinyin: "lǚxíng", italiano: "Viaggiare (per lo più per svago)"},
        {hanzi: "买卖", pinyin: "mǎimai", italiano: "Commercio, affari"},
        {hanzi: "南方", pinyin: "nánfāng", italiano: "Meridione"},
        {hanzi: "其中", pinyin: "qízhōng", italiano: "Fra"},
        {hanzi: "散步", pinyin: "sàn bù", italiano: "Passeggiare"},
        {hanzi: "世界", pinyin: "shìjiè", italiano: "Mondo"},
        {hanzi: "时期", pinyin: "shíqī", italiano: "Periodo di tempo"},
        {hanzi: "通", pinyin: "tōng", italiano: "Conoscitore di qualcosa"},
        {hanzi: "外国", pinyin: "wàiguó", italiano: "Straniero"},
        {hanzi: "吸引", pinyin: "xīyǐn", italiano: "Attirare"},
        {hanzi: "移民", pinyin: "yímín", italiano: "Migrante"},
        {hanzi: "艺术家", pinyin: "yìshùjiā", italiano: "Artista"},
        {hanzi: "游客", pinyin: "yóukè", italiano: "Viaggiatore"},
        {hanzi: "游览", pinyin: "yóulǎn", italiano: "Fare turismo"},
        {hanzi: "愉快", pinyin: "yúkuài", italiano: "Felice, allegro"},
        {hanzi: "占", pinyin: "zhàn", italiano: "Occupare"},
        {hanzi: "政治", pinyin: "zhèngzhì", italiano: "Politica (in senso generico)"},
        {hanzi: "作品", pinyin: "zuòpǐn", italiano: "Opera (artistica)"},
        {hanzi: "威尼斯", pinyin: "Wēinísī", italiano: "Venezia"},
        {hanzi: "佛罗伦萨", pinyin: "fóluólúnsà", italiano: "Firenze"}
    ],

// ===== CAPITOLO 25 =====
    25: [
        {hanzi: "摆", pinyin: "bǎi", italiano: "Collocare, disporre"},
        {hanzi: "保留", pinyin: "bǎoliú", italiano: "Conservare"},
        {hanzi: "冰淇淋", pinyin: "bīngqílín", italiano: "Gelato"},
        {hanzi: "不仅...而且", pinyin: "bùjǐn...érqiě", italiano: "Non solo... ma anche"},
        {hanzi: "常客", pinyin: "chángkè", italiano: "Cliente abituale"},
        {hanzi: "春天", pinyin: "chūntiān", italiano: "Primavera"},
        {hanzi: "大量", pinyin: "dàliàng", italiano: "Gran quantità"},
        {hanzi: "附近", pinyin: "fùjìn", italiano: "Vicinanze"},
        {hanzi: "父亲", pinyin: "fùqin", italiano: "Padre"},
        {hanzi: "挂", pinyin: "guà", italiano: "Appendere"},
        {hanzi: "广场", pinyin: "guǎngchǎng", italiano: "Piazza"},
        {hanzi: "画像", pinyin: "huàxiàng", italiano: "Ritratto"},
        {hanzi: "建造", pinyin: "jiànzào", italiano: "Costruire"},
        {hanzi: "教堂", pinyin: "jiàotáng", italiano: "Chiesa"},
        {hanzi: "街", pinyin: "jiē", italiano: "Via, strada"},
        {hanzi: "聊天儿", pinyin: "liáotiānr", italiano: "Chiacchierare"},
        {hanzi: "年轻", pinyin: "niánqīng", italiano: "Giovane (agg.)"},
        {hanzi: "喷泉", pinyin: "pēnquán", italiano: "Fontana"},
        {hanzi: "品尝", pinyin: "pǐncháng", italiano: "Assaggiare"},
        {hanzi: "墙", pinyin: "qiáng", italiano: "Muro"},
        {hanzi: "其他", pinyin: "qítā", italiano: "Gli altri"},
        {hanzi: "世纪", pinyin: "shìjì", italiano: "Secolo"},
        {hanzi: "时装", pinyin: "shízhuāng", italiano: "Abbigliamento alla moda"},
        {hanzi: "四季", pinyin: "sìjì", italiano: "Quattro stagioni"},
        {hanzi: "台阶", pinyin: "táijiē", italiano: "Gradino, scalinata"},
        {hanzi: "讨论", pinyin: "tǎolùn", italiano: "Discutere"},
        {hanzi: "厅", pinyin: "tīng", italiano: "Sala"},
        {hanzi: "文人", pinyin: "wénrén", italiano: "Uomo di lettere, letterato"},
        {hanzi: "鲜花", pinyin: "xiānhuā", italiano: "Fiore fresco"},
        {hanzi: "欣赏", pinyin: "xīnshǎng", italiano: "Apprezzare"},
        {hanzi: "许多", pinyin: "xǔduō", italiano: "Molti"},
        {hanzi: "有名", pinyin: "yǒumíng", italiano: "Famoso"},
        {hanzi: "原来", pinyin: "yuánlái", italiano: "Originariamente"},
        {hanzi: "站", pinyin: "zhàn", italiano: "Stare in piedi"},
        {hanzi: "照相", pinyin: "zhàoxiàng", italiano: "Fotografare"},
        {hanzi: "着", pinyin: "zhe", italiano: "Particella aspett. che indica azione in corso"},
        {hanzi: "欧洲", pinyin: "Ōuzhōu", italiano: "Europa"},
        {hanzi: "希腊", pinyin: "xīlà", italiano: "Grecia"}
    ],

// ===== CAPITOLO 26 =====
    26: [
        {hanzi: "抱歉", pinyin: "bàoqiàn", italiano: "Dispiaciuto"},
        {hanzi: "参加", pinyin: "cānjiā", italiano: "Partecipare"},
        {hanzi: "差不多", pinyin: "chàbuduō", italiano: "Quasi, più o meno"},
        {hanzi: "出", pinyin: "chū", italiano: "Uscire"},
        {hanzi: "出门", pinyin: "chūmén", italiano: "Uscire, andar fuori"},
        {hanzi: "错", pinyin: "cuò", italiano: "Sbagliato"},
        {hanzi: "到", pinyin: "dào", italiano: "Arrivare"},
        {hanzi: "懂", pinyin: "dǒng", italiano: "Capire"},
        {hanzi: "对话", pinyin: "duìhuà", italiano: "Dialogare, dialogo"},
        {hanzi: "刚才", pinyin: "gāngcái", italiano: "Poco fa"},
        {hanzi: "机会", pinyin: "jīhuì", italiano: "Occasione"},
        {hanzi: "靠", pinyin: "kào", italiano: "Appoggiare, affidarsi a"},
        {hanzi: "篮球", pinyin: "lánqiú", italiano: "Basket, pallacanestro"},
        {hanzi: "另外", pinyin: "língwài", italiano: "Inoltre"},
        {hanzi: "录像带", pinyin: "lùxiàngdài", italiano: "Videocassetta"},
        {hanzi: "录音带", pinyin: "lùyīndài", italiano: "Audiocassetta"},
        {hanzi: "慢", pinyin: "màn", italiano: "Lento"},
        {hanzi: "十分", pinyin: "shífēn", italiano: "Molto (avv.)"},
        {hanzi: "完", pinyin: "wán", italiano: "Finire, terminare"},
        {hanzi: "忘", pinyin: "wàng", italiano: "Dimenticare"},
        {hanzi: "小说", pinyin: "xiǎoshuō", italiano: "Romanzo, novella"},
        {hanzi: "需要", pinyin: "xūyào", italiano: "Aver bisogno di"},
        {hanzi: "糟糕", pinyin: "zāogāo", italiano: "Guaio, accidenti!"},
        {hanzi: "着急", pinyin: "zhāojí", italiano: "Ansioso, agitato"},
        {hanzi: "直接", pinyin: "zhíjiē", italiano: "Direttamente"},
        {hanzi: "字幕", pinyin: "zìmù", italiano: "Sottotitoli"}
    ],

// ===== CAPITOLO 27 =====
    27: [
        {hanzi: "不过", pinyin: "búguò", italiano: "Però"},
        {hanzi: "成为", pinyin: "chéngwéi", italiano: "Diventare"},
        {hanzi: "传统", pinyin: "chuántǒng", italiano: "Tradizione, tradizionale"},
        {hanzi: "打开", pinyin: "dǎkāi", italiano: "Aprire"},
        {hanzi: "发", pinyin: "fā", italiano: "Inviare, mandare"},
        {hanzi: "反对", pinyin: "fǎnduì", italiano: "Opporre, opporsi"},
        {hanzi: "反正", pinyin: "fǎnzhèng", italiano: "Tanto, comunque sia"},
        {hanzi: "放", pinyin: "fàng", italiano: "Mettere, porre"},
        {hanzi: "房租", pinyin: "fángzū", italiano: "Affitto"},
        {hanzi: "关", pinyin: "guān", italiano: "Chiudere"},
        {hanzi: "急", pinyin: "jí", italiano: "Preoccuparsi, agitarsi"},
        {hanzi: "家具", pinyin: "jiājù", italiano: "Mobile"},
        {hanzi: "结婚", pinyin: "jié hūn", italiano: "Sposarsi"},
        {hanzi: "决定", pinyin: "juédìng", italiano: "Decidere"},
        {hanzi: "考虑", pinyin: "kǎolǜ", italiano: "Pensare, riflettere"},
        {hanzi: "恋爱", pinyin: "liàn'ài", italiano: "Innamorarsi"},
        {hanzi: "马上", pinyin: "mǎshàng", italiano: "Subito"},
        {hanzi: "没准儿", pinyin: "méizhǔnr", italiano: "Probabilmente"},
        {hanzi: "奇怪", pinyin: "qíguài", italiano: "Strano, bizzarro"},
        {hanzi: "说服", pinyin: "shuōfú", italiano: "Convincere"},
        {hanzi: "套", pinyin: "tào", italiano: "Serie, set (class.)"},
        {hanzi: "通", pinyin: "tōng", italiano: "Comprendere"},
        {hanzi: "同居", pinyin: "tóngjū", italiano: "Convivere"},
        {hanzi: "同意", pinyin: "tóngyì", italiano: "Consentire, essere d'accordo"},
        {hanzi: "笑话", pinyin: "xiàohua", italiano: "Ridere di qualcuno, barzelletta"},
        {hanzi: "一...就...", pinyin: "yī... jiù...", italiano: "Appena... allora..."},
        {hanzi: "邮件", pinyin: "yóujiàn", italiano: "Posta, messaggio postale"},
        {hanzi: "尤其", pinyin: "yóuqí", italiano: "Soprattutto"},
        {hanzi: "着", pinyin: "zháo", italiano: "Riuscire a raggiungere"},
        {hanzi: "转发", pinyin: "zhuǎnfā", italiano: "Rimandare, inoltrare"},
        {hanzi: "正常", pinyin: "zhèngcháng", italiano: "Normale, regolare"}
    ],

// ===== CAPITOLO 28 =====
    28: [
        {hanzi: "包括", pinyin: "bāokuò", italiano: "Comprendere, includere"},
        {hanzi: "遍", pinyin: "biàn", italiano: "Volta (class. verbale)"},
        {hanzi: "博士", pinyin: "bóshì", italiano: "Dottorato"},
        {hanzi: "成语", pinyin: "chéngyǔ", italiano: "Frase idiomatica"},
        {hanzi: "初中", pinyin: "chūzhōng", italiano: "Scuola media"},
        {hanzi: "打工", pinyin: "dǎgōng", italiano: "Lavorare"},
        {hanzi: "底", pinyin: "dǐ", italiano: "Fine, fondo"},
        {hanzi: "地理", pinyin: "dìlǐ", italiano: "Geografia"},
        {hanzi: "高中", pinyin: "gāozhōng", italiano: "Scuola superiore"},
        {hanzi: "管理", pinyin: "guǎnlǐ", italiano: "Gestire, gestione"},
        {hanzi: "孩子", pinyin: "háizi", italiano: "Bambino"},
        {hanzi: "寒假", pinyin: "hánjià", italiano: "Vacanza invernale"},
        {hanzi: "奖学金", pinyin: "jiǎngxuéjīn", italiano: "Borsa di studio"},
        {hanzi: "经济", pinyin: "jīngjì", italiano: "Economia"},
        {hanzi: "纠正", pinyin: "jiūzhèng", italiano: "Correggere"},
        {hanzi: "继续", pinyin: "jìxù", italiano: "Continuare"},
        {hanzi: "课程", pinyin: "kèchéng", italiano: "Corso di studio"},
        {hanzi: "累", pinyin: "lèi", italiano: "Stanco"},
        {hanzi: "嘛", pinyin: "ma", italiano: "Particella modale (evidenza)"},
        {hanzi: "烹调", pinyin: "pēngtiáo", italiano: "Cucinare"},
        {hanzi: "暑假", pinyin: "shǔjià", italiano: "Vacanza estiva"},
        {hanzi: "硕士", pinyin: "shuòshì", italiano: "Laurea specialistica o magistrale"},
        {hanzi: "数学", pinyin: "shùxué", italiano: "Matematica"},
        {hanzi: "外贸", pinyin: "wàimào", italiano: "Commercio estero"},
        {hanzi: "学年", pinyin: "xuénián", italiano: "Anno accademico"},
        {hanzi: "学期", pinyin: "xuéqī", italiano: "Semestre, periodo scolastico"},
        {hanzi: "研究生", pinyin: "yánjiūshēng", italiano: "Dottorando"},
        {hanzi: "遗憾", pinyin: "yíhàn", italiano: "Rimpianto, dispiaciuto"},
        {hanzi: "语文", pinyin: "yǔwén", italiano: "Lettere (materia)"},
        {hanzi: "职业", pinyin: "zhíyè", italiano: "Professione"},
        {hanzi: "自费", pinyin: "zìfèi", italiano: "A proprie spese"},
        {hanzi: "自食其力", pinyin: "zì shí qí lì", italiano: "Vivere del proprio lavoro"}
    ],


    // ===== CAPITOLO 29 =====
    29: [
        {hanzi: "把", pinyin: "bǎ", italiano: "Part. che anticipa il c.o. prima del predicato"},
        {hanzi: "把", pinyin: "bǎ", italiano: "Class. per gli oggetti che si afferrano, manciata"},
        {hanzi: "搬", pinyin: "bān", italiano: "Traslocare, spostare"},
        {hanzi: "便条", pinyin: "biàntiáo", italiano: "Biglietto, messaggio"},
        {hanzi: "冰箱", pinyin: "bīngxiāng", italiano: "Frigorifero"},
        {hanzi: "布置", pinyin: "bùzhi", italiano: "Sistemare, abbellire"},
        {hanzi: "擦", pinyin: "cā", italiano: "Strofinare, pulire"},
        {hanzi: "床", pinyin: "chuáng", italiano: "Letto"},
        {hanzi: "厨房", pinyin: "chúfáng", italiano: "Cucina"},
        {hanzi: "道理", pinyin: "dàoli", italiano: "Ragione"},
        {hanzi: "打扫", pinyin: "dǎsǎo", italiano: "Fare le pulizie"},
        {hanzi: "顿", pinyin: "dùn", italiano: "Pasto (class.)"},
        {hanzi: "放", pinyin: "fàng", italiano: "Mettere"},
        {hanzi: "感到", pinyin: "gǎndào", italiano: "Sentire, provare"},
        {hanzi: "脚", pinyin: "jiǎo", italiano: "Piede"},
        {hanzi: "可口", pinyin: "kěkǒu", italiano: "Gustoso"},
        {hanzi: "客厅", pinyin: "kètīng", italiano: "Salone"},
        {hanzi: "梦", pinyin: "mèng", italiano: "Sogno"},
        {hanzi: "迷信", pinyin: "míxìn", italiano: "Superstizione, superstizioso"},
        {hanzi: "巧克力", pinyin: "qiǎokèlì", italiano: "Cioccolato"},
        {hanzi: "食堂", pinyin: "shítáng", italiano: "Mensa"},
        {hanzi: "实现", pinyin: "shíxiàn", italiano: "Realizzare, mettere in pratica"},
        {hanzi: "它", pinyin: "tā", italiano: "Esso (per cose e animali)"},
        {hanzi: "头", pinyin: "tóu", italiano: "Testa"},
        {hanzi: "晚餐", pinyin: "wǎncān", italiano: "Cena"},
        {hanzi: "卫生", pinyin: "wèishēng", italiano: "Igienico, igiene"},
        {hanzi: "卫生间", pinyin: "wèishēngjiān", italiano: "Sala da bagno"},
        {hanzi: "位置", pinyin: "wèizhi", italiano: "Posizione"},
        {hanzi: "吻", pinyin: "wěn", italiano: "Baciare, bacio"},
        {hanzi: "卧室", pinyin: "wòshì", italiano: "Camera da letto"},
        {hanzi: "香", pinyin: "xiāng", italiano: "Profumato"},
        {hanzi: "辛苦", pinyin: "xīnkǔ", italiano: "Affaticarsi"},
        {hanzi: "醒", pinyin: "xǐng", italiano: "Svegliare, svegliarsi"}
    ],

// ===== CAPITOLO 30 =====
    30: [
        {hanzi: "幸福", pinyin: "xìngfú", italiano: "Felicità, felice"},
        {hanzi: "椅子", pinyin: "yǐzi", italiano: "Sedia"},
        {hanzi: "愿望", pinyin: "yuànwàng", italiano: "Desiderio"},
        {hanzi: "终于", pinyin: "zhōngyú", italiano: "Finalmente"},
        {hanzi: "按", pinyin: "àn", italiano: "Pressare (suonare)"},
        {hanzi: "白头到老", pinyin: "bái tóu dào lǎo", italiano: "Invecchiare insieme"},
        {hanzi: "菜市场", pinyin: "càishìchǎng", italiano: "Mercato ortofrutticolo"},
        {hanzi: "草", pinyin: "cǎo", italiano: "Erba"},
        {hanzi: "层", pinyin: "céng", italiano: "Piano (class.)"},
        {hanzi: "答应", pinyin: "dāying", italiano: "Promettere, acconsentire"},
        {hanzi: "读书", pinyin: "dú shū", italiano: "Studiare"},
        {hanzi: "对", pinyin: "duì", italiano: "Coppia (class.)"},
        {hanzi: "高", pinyin: "gāo", italiano: "Alto"},
        {hanzi: "孤独", pinyin: "gūdú", italiano: "In solitudine, solo"},
        {hanzi: "好奇", pinyin: "hàoqí", italiano: "Curioso"},
        {hanzi: "花", pinyin: "huā", italiano: "Fiore"},
        {hanzi: "环境", pinyin: "huánjìng", italiano: "Ambiente"},
        {hanzi: "吉祥", pinyin: "jíxiáng", italiano: "Fausto"},
        {hanzi: "吉祥物", pinyin: "jíxiángwù", italiano: "Portafortuna"},
        {hanzi: "来往", pinyin: "láiwǎng", italiano: "Avere contatti, scambi"},
        {hanzi: "老", pinyin: "lǎo", italiano: "Vecchio, anziano (agg.)"},
        {hanzi: "老人", pinyin: "lǎorén", italiano: "Anziano (sost.)"},
        {hanzi: "邻居", pinyin: "línjū", italiano: "Vicino (di casa)"},
        {hanzi: "铃", pinyin: "líng", italiano: "Campanello"},
        {hanzi: "树", pinyin: "shù", italiano: "Albero"},
        {hanzi: "温馨", pinyin: "wēnxīn", italiano: "Dolce (ambiente o atmosfera)"},
        {hanzi: "物", pinyin: "wù", italiano: "Oggetto"},
        {hanzi: "相亲相爱", pinyin: "xiāngqīn xiāng'ài", italiano: "Amarsi e apprezzarsi"},
        {hanzi: "中国结", pinyin: "zhōngguójié", italiano: "Nodi cinesi"},
        {hanzi: "周围", pinyin: "zhōuwéi", italiano: "Dintorni"},
        {hanzi: "祝", pinyin: "zhù", italiano: "Augurare"},
        {hanzi: "祝贺", pinyin: "zhùhé", italiano: "Augurare, augurio"}
    ],

// ===== CAPITOLO 31 =====
    31: [
        {hanzi: "报名", pinyin: "bào míng", italiano: "Iscriversi"},
        {hanzi: "保证", pinyin: "bǎozhèng", italiano: "Garantire, garanzia"},
        {hanzi: "笔", pinyin: "bǐ", italiano: "Class. somma di denaro"},
        {hanzi: "表格", pinyin: "biǎogé", italiano: "Modulo"},
        {hanzi: "必须", pinyin: "bìxū", italiano: "Dovere (verbo aus.)"},
        {hanzi: "出租汽车", pinyin: "chūzūqìchē", italiano: "Taxi"},
        {hanzi: "打印", pinyin: "dǎyìn", italiano: "Stampare"},
        {hanzi: "堵", pinyin: "dǔ", italiano: "Congestionare, otturare"},
        {hanzi: "够", pinyin: "gòu", italiano: "Sufficiente"},
        {hanzi: "护照", pinyin: "hùzhào", italiano: "Passaporto"},
        {hanzi: "交", pinyin: "jiāo", italiano: "Pagare, consegnare"},
        {hanzi: "交通", pinyin: "jiāotōng", italiano: "Traffico, trasporti"},
        {hanzi: "快要", pinyin: "kuàiyào", italiano: "Rapidamente"},
        {hanzi: "礼节", pinyin: "lǐjié", italiano: "Costumi, usanze"},
        {hanzi: "签证", pinyin: "qiānzhèng", italiano: "Visto (sost.)"},
        {hanzi: "情况", pinyin: "qíngkuàng", italiano: "Situazione"},
        {hanzi: "上班", pinyin: "shàng bān", italiano: "Andare a lavorare"},
        {hanzi: "手表", pinyin: "shǒubiǎo", italiano: "Orologio da polso"},
        {hanzi: "收", pinyin: "shōu", italiano: "Ricevere"},
        {hanzi: "首先", pinyin: "shǒuxiān", italiano: "Dapprima (cong.)"},
        {hanzi: "手续", pinyin: "shǒuxù", italiano: "Formalità, pratiche burocratiche"},
        {hanzi: "双人间", pinyin: "shuāngrénjiān", italiano: "Camera doppia"},
        {hanzi: "宿舍", pinyin: "sùshè", italiano: "Dormitorio"},
        {hanzi: "填", pinyin: "tián", italiano: "Riempire, compilare"},
        {hanzi: "通知", pinyin: "tōngzhī", italiano: "Dare comunicazione, avviso"},
        {hanzi: "小吃", pinyin: "xiǎochī", italiano: "Spuntino"},
        {hanzi: "下载", pinyin: "xiàzài", italiano: "Scaricare"},
        {hanzi: "兴奋", pinyin: "xīngfèn", italiano: "Eccitato"},
        {hanzi: "选", pinyin: "xuǎn", italiano: "Scegliere"},
        {hanzi: "学费", pinyin: "xuéfèi", italiano: "Tasse scolastiche"},
        {hanzi: "预定", pinyin: "yùdìng", italiano: "Prenotare"}
    ],

// ===== CAPITOLO 32 =====
    32: [
        {hanzi: "只要...就...", pinyin: "zhǐyào... jiù...", italiano: "Basta che... allora..."},
        {hanzi: "只有...才...", pinyin: "zhǐyǒu... cái...", italiano: "Solo se... allora..."},
        {hanzi: "注意", pinyin: "zhùyì", italiano: "Prestare attenzione"},
        {hanzi: "安排", pinyin: "ānpái", italiano: "Organizzare, sistemare"},
        {hanzi: "办公室", pinyin: "bàngōngshì", italiano: "Ufficio"},
        {hanzi: "包", pinyin: "bāo", italiano: "Borsa"},
        {hanzi: "电梯", pinyin: "diàntī", italiano: "Ascensore"},
        {hanzi: "干净", pinyin: "gānjìng", italiano: "Pulito"},
        {hanzi: "海关", pinyin: "hǎiguān", italiano: "Dogana"},
        {hanzi: "架", pinyin: "jià", italiano: "Class. per gli apparecchi"},
        {hanzi: "检查", pinyin: "jiǎnchá", italiano: "Controllare"},
        {hanzi: "警察", pinyin: "jǐngchá", italiano: "Poliziotto, polizia"},
        {hanzi: "领导", pinyin: "lǐngdǎo", italiano: "Leader, dirigente"},
        {hanzi: "领队", pinyin: "lǐngduì", italiano: "Capogruppo"},
        {hanzi: "满", pinyin: "mǎn", italiano: "Pieno, completo"},
        {hanzi: "跑", pinyin: "pǎo", italiano: "Correre"},
        {hanzi: "取", pinyin: "qǔ", italiano: "Prendere"},
        {hanzi: "日程", pinyin: "rìchéng", italiano: "Calendario giornaliero"},
        {hanzi: "日用品", pinyin: "rìyòngpǐn", italiano: "Oggetti di uso quotidiano"},
        {hanzi: "书架", pinyin: "shūjià", italiano: "Libreria, scaffale"},
        {hanzi: "顺利", pinyin: "shùnlì", italiano: "Tranquillo (svolgimento)"},
        {hanzi: "头儿", pinyin: "tóur", italiano: "Capo"},
        {hanzi: "网吧", pinyin: "wǎngbā", italiano: "Internet cafè"},
        {hanzi: "箱子", pinyin: "xiāngzi", italiano: "Valigia"},
        {hanzi: "西餐", pinyin: "xīcān", italiano: "Cucina occidentale"},
        {hanzi: "行李", pinyin: "xíngli", italiano: "Bagaglio"},
        {hanzi: "阅览室", pinyin: "yuèlǎnshì", italiano: "Sala di lettura"},
        {hanzi: "照相机", pinyin: "zhàoxiàngjī", italiano: "Macchina fotografica"},
        {hanzi: "中餐", pinyin: "zhōngcān", italiano: "Cucina cinese"},
        {hanzi: "注册", pinyin: "zhùcè", italiano: "Registrarsi"}
    ]

};

// Funzione per sanitizzare ID (rimuove caratteri non validi per Firebase)
function sanitizeId(str) {
    return str.replace(/[.#$\/\[\]]/g, '_');
}

const vocaboli = Object.entries(wordsByLesson).flatMap(([capitolo, parole]) =>
    parole.map(p => ({
        id: sanitizeId(`${capitolo}_${p.hanzi}_${p.pinyin}`),
        ...p,
        capitolo
    }))
);